-- phpMyAdmin SQL Dump
-- version 5.1.1-1.el7.remi
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 25, 2026 at 08:33 PM
-- Server version: 10.6.4-MariaDB
-- PHP Version: 7.4.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `grsshopper`
--

-- --------------------------------------------------------

--
-- Table structure for table `fallacy`
--

CREATE TABLE `fallacy` (
  `fallacy_id` int(11) NOT NULL,
  `fallacy_crdate` int(15) DEFAULT NULL,
  `fallacy_creator` int(15) DEFAULT NULL,
  `fallacy_title` varchar(124) DEFAULT NULL,
  `fallacy_latin` varchar(124) DEFAULT NULL,
  `fallacy_description` text DEFAULT NULL,
  `fallacy_proof` text DEFAULT NULL,
  `fallacy_category` varchar(64) DEFAULT NULL,
  `fallacy_definition` text DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `fallacy`
--

INSERT INTO `fallacy` (`fallacy_id`, `fallacy_crdate`, `fallacy_creator`, `fallacy_title`, `fallacy_latin`, `fallacy_description`, `fallacy_proof`, `fallacy_category`, `fallacy_definition`) VALUES
(1, 1643917569, 1, 'False Dilemma', NULL, 'Definition: A limited number of options (usually two) is given, while in reality there are more options. A false dilemma is an illegitimate use of the \"or\" operator.', 'Identify the options given and show (with an example) that there is an additional option. (Cedarblom and Paulsen: 136)', 'distraction', 'Two choices are given when in fact there are three options'),
(2, 1643918641, 1, 'Argument From Ignorance', 'argumentum ad ignorantiam', 'Arguments of this form assume that since something has not been proven false, it is therefore true. Conversely, such an argument may assume that since something has not been proven true, it is therefore false. (This is a special case of a false dilemma, since it assumes that all propositions must ether be known to be true or known to be false.) As Davis writes, \"Lack of proof is not proof.\" (p. 59)', 'Identify the proposition in question. Argue that it may be true even though we don&#39;t know whether it is or isn&#39;t. (Copi and Cohen: 93, Davis: 59)', 'distraction', 'Because something is not known to be true, it is assumed to be false'),
(3, 1643919454, 1, 'Slippery Slope', NULL, 'In order to show that a proposition P is unacceptable, a sequence of increasingly unacceptable events is shown to follow from P. A slippery slope is an illegitimate use of the\"if-then\" operator.', 'Identify the proposition P being refuted and identify the final event in the series of events. Then show that this final event need not occur as a consequence of P. (Cedarblom and Paulsen: 137)', 'distraction', 'A series of increasingly unacceptable consequences is drawn'),
(4, 1644103699, 3, 'Complex Question', NULL, 'Two otherwise unrelated points are conjoined and treated as a single proposition. The reader is expected to accept or reject both together, when in reality one is acceptable while the other is not. A complex question is an illegitimate use of the \"and\" operator.', 'Identify the two propositions illegitimately conjoined and show that believing one does not mean that you have to believe the other. (Cedarblom and Paulsen: 86, Copi and Cohen: 96)', 'distraction', 'Two unrelated points are conjoined as a single proposition'),
(5, 1644103873, 3, 'Appeal to Force', 'argumentum ad baculum', 'The reader is told that unpleasant consequences will follow if they do not agree with the author.', 'Identify the threat and the proposition and argue that the threat is unrelated to the truth or falsity of the proposition. (Cedarblom and Paulsen: 151, Copi and Cohen: 103)', 'motives', 'The reader is persuaded to agree by force'),
(6, 1644104007, 3, 'Appeal to Pity', 'argumentum ad misercordiam', 'The reader is told to agree to the proposition because of the pitiful state of the author. ', 'Identify the proposition and the appeal to pity and argue that the pitiful state of the arguer has nothing to do with the truth of the proposition. (Cedarblom and Paulsen: 151, Copi and Cohen: 103, Davis: 82)', 'motives', 'The reader is persuaded to agree by sympathy'),
(7, 1644104115, 3, 'Appeal to Consequences', 'argumentum ad consequentiam', 'The author points to the disagreeable consequences of holding a particular belief in order to show that this belief is false. ', 'Identify the consequences to and argue that what we want to be the case does not affect what is in fact the case. (Cedarblom and Paulsen: 100, Davis: 63)', 'motives', 'The reader is warned of unacceptable consequences'),
(8, 1644104231, 3, 'Prejudicial Language', NULL, 'Loaded or emotive terms are used to attach value or moral goodness to believing the proposition.', 'Identify the prejudicial terms used (eg. \"Right thinking Canadians\" or \"A reasonable person\"). Show that disagreeing with the conclusion does not make a person \"wrong thinking\" or \"unreasonable\". (Cedarblom and Paulsen: 153, Davis: 62)', 'motives', 'Value or moral goodness is attached to believing the author'),
(9, 1644104427, 3, 'Appeal to Popularity', 'argumentum ad populum', ' or is held to be true by some (usually upper crust) sector of the population. This fallacy is sometimes also called the \"Appeal to Emotion\" because emotional appeals often sway the population as a whole.', 'Identity how the popularity of the belief is used as evidence that the belief is true.  (Copi and Cohen: 103, Davis: 62)', 'motives', 'A proposition is argued to be true because it is widely held to be true'),
(13, 1644105320, 3, 'Anonymous Authorities', NULL, 'The authority in question is not named. This is a type of appeal to authority because when an authority is not named it is impossible to confirm that the authority is an expert. However the fallacy is so common it deserves special mention. A variation on this fallacy is the appeal to rumour. Because the source of a rumour is typically not known, it is not possible to determine whether to believe the rumour. Very often false and harmful rumours are deliberately started n order to discredit an opponent.', 'Proof: Argue that because we don&#39;t know the source of the information we have no way to evaluate the reliability of the information. (Davis: 73)', 'subject', 'The authority in question is not named\n'),
(23, 1644108754, 3, 'Coincidental Correlation', 'post hoc ergo propter hoc', 'The name in Latin means \"after this therefore because of this\". This describes the fallacy. An author commits the fallacy when it is assumed that because one thing follows another that the one thing was caused by the other.', 'Show that the correlation is coincidental by showing that: (i)the effect would have occurred even if the cause did not occur, or (ii) that the effect was caused by something other than the suggested cause. (Cedarblom and Paulsen: 237, Copi and Cohen: 101)', 'causal', 'Because one thing follows another, it is held to cause the other'),
(11, 1644104801, 3, 'Attacking the Person', 'argumentum ad hominem', 'The person presenting an argument is attacked instead of the argument itself. This takes many forms. For example, the person&#39;s character, nationality or religion may be attacked. Alternatively, it may be pointed out that a person stands to gain from a favourable outcome. Or, finally, a person may be attacked by association, or by the company he keeps. There are three major forms of Attacking the Person:\n(1) ad hominem (abusive): instead of attacking an assertion, the argument attacks the person who made the assertion.\n\n(2) ad hominem (circumstantial): instead of attacking an assertion the author points to the relationship between the person making the assertion and the person&#39;s circumstances.\n\n(3) ad hominem (tu quoque): this form of attack on the person notes that a person does not practise what he preaches.', 'Identify the attack and show that the character or circumstances of the person has nothing to do with the truth or falsity of the proposition being defended. (Barker: 166, Cedarblom and Paulsen: 155, Copi and Cohen: 97, Davis: 80)', 'subject', 'The person&#39;s character is attacked, the person&#39;s circumstances are noted, or the person does not practice what is preached\n'),
(12, 1644105017, 3, 'Appeal to Authority', 'argumentum ad verecundiam', 'While sometimes it may be appropriate to cite an authority to support a point, often it is not. In particular, an appeal to authority is inappropriate if:\n\n(i) the person is not qualified to have an expert opinion on the subject,\n\nii) experts in the field disagree on this issue.\n\n(iii) the authority was making a joke, drunk, or otherwise not being serious\n\nA variation of the fallacious appeal to authority is hearsay. An argument from hearsay is an argument which depends on second or third hand sources. ', 'Show that either (i) the person cited is not an authority in the field, or that (ii) there is general disagreement among the experts in the field on this point. (Cedarblom and Paulsen: 155, Copi and Cohen: 95, Davis: 69)', 'subject', 'The authority is not an expert in the field, experts in the field disagree, or the authority was joking, drunk, or in some other way not being serious\n\n\n(i) the person is not qualified to have an expert opinion on the subject,\n\nii) experts in the field disagree on this issue.\n\n(iii) the authority was making a joke, drunk, or otherwise not being serious\n\nA variation of the fallacious appeal to authority is hearsay. An argument from hearsay is an argument which depends on second or third hand sources. '),
(22, 1644108351, 3, 'Converse Accident', NULL, 'An exception to a generalization is applied to cases where the generalization should apply.', 'Identify the generalization in question and show how the special case was an exception to the generalization. (Copi and Cohen: 100)', 'statistical', 'An exception is applied in circumstances where a generalization should apply'),
(15, 1644105573, 3, 'Style Over Substance', NULL, 'The manner in which an argument (or arguer) is presented is taken to affect the likelihood that the conclusion is true. While it is true that the manner in which an argument is presented will affect whether people believe that its conclusion is true, nonetheless, the truth of the conclusion does not depend on the manner in which the argument is presented. ', 'In order to show that this fallacy is being committed, show that the style in this case does not affect the truth or falsity of the conclusion. (Davis: 61)', NULL, 'The manner in which an argument (or arguer) is presented is felt to affect the truth of the conclusion'),
(16, 1644105630, 3, 'Unrepresentative Sample', NULL, 'The sample used in an inductive inference is relevantly different from the population as a whole.', 'Show how the sample is relevantly different from the population as a whole, then show that because the sample is different, the conclusion is probably different. (Barker: 188, Cedarblom and Paulsen: 226, Davis: 106)', 'inductive', 'The sample is unrepresentative of the population as a whole'),
(17, 1644105710, 3, 'Hasty Generalization', NULL, 'The size of the sample is too small to support the conclusion. Examples: (i) Fred, the Australian, stole my wallet. Thus, all Australians are thieves. (Of course, we shouldn&#39;t judge all Australians on the basis of one example.)', 'Identify the size of the sample and the size of the population,then show that the sample size is too small. Note: a formal proof would require a mathematical calculation. This is the subject of probability theory. For now, you must rely on common sense. (Barker: 189, Cedarblom and Paulsen: 372, Davis: 103)', 'inductive', 'The sample is too small to support an inductive generalization about a population\n'),
(18, 1644105932, 3, 'False Analogy', NULL, 'In an analogy, two objects (or events), A and B are shown to be similar. Then it is argued that since A has property P, so also B must have property P. An analogy fails when the two objects, A and B, are different in a way which affects whether they both have property P.', 'Identify the two objects or events being compared and the property which both are said to possess. Show that the two objects are different in a way which will affect whether they both have that property. (Barker: 192, Cedarblom and Paulsen: 257, Davis: 84)', 'inductive', 'The two objects or events being compared are relevantly dissimilar'),
(19, 1644106031, 3, 'Slothful Induction ', NULL, 'The proper conclusion of an inductive argument is denied despite the evidence to the contrary.', 'About all you can do in such a case is to point to the strength of the inference. (Barker: 189)', NULL, 'The conclusion of a strong inductive argument is denied despite the evidence to the contrary'),
(20, 1644106139, 3, 'Fallacy of Exclusion', NULL, 'Important evidence which would undermine an inductive argument is excluded from consideration. The requirement that all relevant information be included is called the \"principle of total evidence\".', 'Give the missing evidence and show that it changes the outcome of the inductive argument. Note that it is not sufficient simply to show that not all of the evidence was included; it must be shown that the missing evidence will change the conclusion. (Davis: 115)\n\n', NULL, 'Evidence which would change the outcome of an inductive argument is excluded from consideration'),
(21, 1644108136, 3, 'Accident', NULL, 'A general rule is applied when circumstances suggest that an exception to the rule should apply.', 'Identify the generalization in question and show that it s not a universal generalization. Then show that the circumstances of this case suggest that the generalization ought not to apply. (Copi and Cohen: 100)', 'statistical', 'A generalization is applied when circumstances suggest that there should be an exception'),
(24, 1644108912, 3, 'Joint Effect ', NULL, 'One thing is held to cause another when in fact both are the effect of a single underlying cause. This fallacy is often understood as a special case of post hoc ergo propter hoc.', ' Identify the two effects and show that they are caused by the same underlying cause. It is necessary to describe the underlying cause and prove that it causes each symptom. (Cedarblom and Paulsen: 238)', 'causal', 'One thing is held to cause another when in fact they are both the joint effects of an underlying cause'),
(25, 1644109076, 3, 'Genuine but Insignificant Cause', NULL, 'The object or event identified as the cause of an effect is a genuine cause, but insignificant when compared to the other causes of that event. Note that this fallacy does not apply when all other contributing causes are equally insignificant. Thus, it is not a fallacy to say that you helped cause defeat the Tory government because you voted Reform, for your vote had as much weight as any other vote, and hence is equally a part of the cause. ', 'Identify the much more significant cause. (Cedarblom and Paulsen: 238)', 'causal', 'One thing is held to cause another, and it does, but it is insignificant compared to other causes of the effect'),
(26, 1644109274, 3, 'Wrong Direction', NULL, 'The relation between cause and effect is reversed. That which is identified as the effect is actually the cause.', 'Give a causal argument showing that the relation between cause and effect has been reversed. (Cedarblom and Paulsen: 238)', 'causal', 'The direction between cause and effect is reversed'),
(27, 1644109431, 3, 'Complex Cause', NULL, 'The effect is caused by a number of objects or events, of which the cause identified is only a part. A variation of this is the feedback loop where the effect is itself a part of the cause.', 'Show that all of the causes, and not just the one mentioned, are required to produce the effect. (Cedarblom and Paulsen: 238)', 'causal', 'The cause identified is only a part of the entire cause of the effect'),
(28, 1644109632, 3, 'Begging the Question', 'petitio principii', 'The truth of the conclusion is assumed by the premises. Often, the conclusion is simply restated in the premises in a slightly different form. In more difficult cases, the premise is a consequence of the conclusion.', 'Show that in order to believe that the premises are true we must already agree that the conclusion is true. (Barker: 159, Cedarblom and Paulsen: 144, Copi and Cohen: 102, Davis: 33)', 'point', 'The truth of the conclusion is assumed by the premises'),
(29, 1644109757, 3, 'Irrelevant Conclusion', 'ignoratio elenchi', 'An argument which purports to prove one thing instead proves a different conclusion.', 'Show that the conclusion proved by the author is not the conclusion that the author set out to prove. (Copi and Cohen: 105)', 'point', 'An argument in defense of one conclusion instead proves a different conclusion'),
(30, 1644109914, 3, 'Straw Man', NULL, 'The author attacks an argument which is different from, and usually weaker than, the opposition&#39;s best argument.', 'Show that the opposition&#39;s argument has been misrepresented by showing that the opposition has a stronger argument. Describe the stronger argument. (Cedarblom and Paulsen: 138)', 'point', 'The author attacks an argument different from (and weaker than) the opposition&#39;s best argument'),
(31, 1644157290, 3, 'Equivocation', NULL, 'The same term is used with two different meanings. There are two ways in which this can occur.\n(i) The word or phrase may be ambiguous, in which case it has more than one distinct meaning.\n(ii) The word or phrase may be vague, in which case it has no distinct meaning.', 'Identify the word which is used twice, then show that a definition which is appropriate for one use of the word would not be appropriate for the second use. (Barker: 163, Cedarblom and Paulsen: 142, Copi and Cohen: 113, Davis: 58)', 'ambiguity', 'The same term is used with two different meanings'),
(32, 1644157589, 3, 'Amphiboly', NULL, 'An amphiboly occurs when the construction of a sentence allows it to have two different meanings.', 'Identify the ambiguous phrase and show the two possible interpretations. (Copi and Cohen: 114)', 'ambiguity', 'The structure of a sentence allows two different interpretations'),
(33, 1644157878, 3, 'Accent', NULL, 'Emphasis is used to suggest a meaning different from the actual content of the proposition.', 'Identify the part being emphasized, note the meaning of that part, and show that it is different from the meaning of the whole.', 'ambiguity', 'The emphasis on a word or phrase suggests a meaning contrary to what the sentence actually says'),
(34, 1644158213, 3, 'Composition ', NULL, 'Because the parts of a whole have a certain property, it is argued that the whole has that property. That whole may be either an object composed of different parts, or it may be a collection or set of individual members. ', 'Show that the properties in question are the properties of the whole, and not of each part or member or the whole. If necessary, describe the parts to show that they could not have the properties of the whole. (Barker: 164, Copi and Cohen: 117)', 'category', 'Because the parts have a certain property, it is argued that the whole has that property'),
(35, 1644158383, 3, 'Division', NULL, 'Because the whole has a certain property, it is argued that the parts have that property. The whole in question may be either a whole object or a collection or set of individual members.', 'Show that the properties in question are the properties of the whole, and not of each part or member or the whole. If necessary, describe the parts to show that they could not have the properties of the whole. (Barker: 164, Copi and Cohen: 117)', NULL, 'Because the whole has a certain property, it is argued that the parts have that property'),
(36, 1644159098, 3, 'Affirming the Consequent', NULL, 'Any argument of the following form is invalid:\n\nIf A happens then B will happen (First premiss)\nB happened (Second premiss)\nTherefore, A happened (Conclusion)', 'Show that even though the premises are true, the conclusion could be false. In general, show that B might be a consequence of something other than A. For example, the fish deaths might be caused by pesticide run-off, and not the mill. (Barker: 69, Cedarblom and Paulsen: 24, Copi and Cohen: 241)', 'nonsequitur', 'Any argument of the form: If A then B, B, therefore A'),
(37, 1644159284, 3, 'Denying the Antecedent', NULL, 'Any argument of the following form is invalid:\n\nIf A happens then B will happen (First premiss)\nA did not happen. (Second premiss)\nTherefore, B did not happen. (Conclusion)', 'Show that even though the premises are true, the conclusion may be false. In particular, show that the consequence B may occur even though A does not occur. (Barker: 69, Cedarblom and Paulsen: 26, Copi and Cohen: 241)', 'nonsequitur', 'Any argument of the form: If A then B, Not A, thus Not B'),
(38, 1644159417, 3, 'Inconsistency', NULL, 'The author asserts more than one proposition such that the propositions cannot all be true. In such a case, the propositions may be contradictories or they may be contraries.', 'Assume that one of the statements is true, and then use it as a premise to show that one of the other statements is false. (Barker: 157) ', 'nonsequitur', 'Asserting that contrary or contradictory statements are both true'),
(39, 1644159924, 3, 'Fallacy of Four Terms', NULL, 'A standard form categorical syllogism contains four terms. See https://web.archive.org/web/20150108200256/http://www.fallacies.ca/cat_form.htm', 'Identify the four terms and where necessary state the meaning of each term. ', 'syllogistic', 'A syllogism has four terms'),
(40, 1644160106, 3, 'Undistributed Middle', NULL, 'The middle term in the premises of a standard form categorical syllogism never refers to all of the members of the category it describes. ', '     Show how each of the two categories identified in the conclusion could be separate groups even though they share a common property. Copi and Cohen: 207 ', 'syllogistic', 'Two separate categories are said to be connected because they share a common property'),
(41, 1644160334, 3, 'Illicit Major', NULL, 'The predicate term of the conclusion refers to all members of that category, but the same term in the premises refers only to some members of that category. ', 'Show that there may be other members of the predicate category not mentioned in the premises which are contrary to the conclusion.\n\nFor example, from (i) above, one might argue, \"While it&#39;s true that all Texans are Americans, it is also true that Ronald Regan is American, but Ronald Regan is Californian, so it is not true that No Californians are Americans.\" ', 'syllogistic', 'The predicate of the conclusion talks about all of something, but the premises only refer to some of them.'),
(42, 1644160522, 3, 'Illicit Minor', NULL, 'The subject term of the conclusion refers to all members of that category, but the same term in the premises refers only to some members of that category. ', '     Show that there may be other members of the subject category not mentioned in the premises which are contrary to the conclusion.\n\n    For example, from (i) above, one might argue, \"While it&#39;s true that all communists are critics of capitalism, it is also true that Thomas Jefferson was a critic of capitalism, but Thomas Jefferson was not a subversive, so not all critics of capitalism are subversives.\"  Copi and Cohen: 208 ', 'syllogistic', 'The subject of the conclusion talks about all of something, but the premises only refer to some of them.'),
(43, 1644160837, 3, 'Fallacy of Exclusive Premises', NULL, 'The fallacy of exclusive premises is a syllogistic fallacy committed in a categorical syllogism that is invalid because both of its premises are negative.', 'Show that the two premises are negative. Nothing follows from two negatives.', 'syllogistic', 'A syllogism has two negative premises'),
(44, 1644161305, 3, 'Drawing an Affirmative Conclusion From a Negative Premise', NULL, 'The conclusion of a standard form categorical syllogism is affirmative, but at least one of the premises is negative. ', 'Assume that the premises are true. Find an example which allows the premises to be true but which clearly contradicts the conclusion. Copi and Cohen: 210', NULL, 'As the name implies'),
(45, 1644161484, 3, 'Existential Fallacy', NULL, 'A standard form categorical syllogism with two universal premises has a particular conclusion.\n\nThe idea is that some universal properties need not be instantiated. It may be true that &#39;all trespassers will be shot&#39; even if there are no trespassers. It may be true that &#39;all brakeless trains are dangerous&#39; even though there are no brakeless trains. That is the point of this fallacy.', '     Assume that the premises are true, but that there are no instances of the category described. For example, in (i) above, assume there are no mice, and in (ii) above, assume there are no honest people. This shows that the conclusion is false. Copi and Cohen: 210 ', NULL, 'A particular conclusion is drawn from universal premises'),
(46, 1644164261, 3, 'Subverted Support', NULL, 'An explanation is intended to explain who some phenomenon happens. The explanation is fallacious if the phenomenon does not actually happen of if there is no evidence that it does happen.', 'Identify the phenomenon being explained. Show that there is no reason to believe that the phenomenon has actually occurred. Cedarblom and Paulsen: 158 ', 'explanation', 'The phenomenon being explained doesn&#39;t exist'),
(47, 1644164507, 3, 'Non-Support', NULL, 'An explanation is intended to explain who some phenomenon happens. In this case, there is evidence that the phenomenon occurred, but it is trumped up, biased or ad hoc evidence. ', 'Identify the phenomenon which is being explained. Show that the evidence advanced to support the existence of the phenomenon was manipulated in some way. Cedarblom and Paulsen: 160 ', 'explanation', 'Evidence for the phenomenon being explained is biased'),
(48, 1644164688, 3, 'Untestability', NULL, 'The theory advanced to explain why some phenomenon occurs cannot be tested. We test a theory by means of its predictions. For example, a theory may predict that light bends under certain conditions, or that a liquid will change colour if sprayed with acid, or that a psychotic person will respond badly to particular stimuli. If the predicted event fails to occur, then this is evidence against the theory.\nA theory cannot be tested when it makes no predictions. It is also untestable when it predicts events which would occur whether or not the theory were true.  ', 'Identify the theory. Show that it makes no predictions, or that the predictions it does make cannot ever be wrong, even if the theory is false.  Cedarblom and Paulsen: 161 ', 'explanation', 'The theory that explains cannot be tested'),
(49, 1644165050, 3, 'Limited Scope ', NULL, 'The theory doesn&#39;t explain anything other than the phenomenon it explains. ', 'Identify the theory and the phenomenon it explains. Show that the theory does not explain anything else. Argue that theories which explain only one phenomenon are likely to be incomplete, at best.\nCedarblom and Paulsen: 163', 'explanation', 'The theory that explains can only explain one thing'),
(50, 1644165235, 3, 'Limited Depth', NULL, 'Theories explain phenomena by appealing to some underlying cause or phenomena. Theories which do not appeal to an underlying cause, and instead simply appeal to membership in a category, commit the fallacy of limited depth. ', 'Theories of this sort attempt to explain a phenomenon by showing that it is part of a category of similar phenomenon. Accept this, then press for an explanation of the wider category of phenomenon. Argue that a theory refers to a cause, not a classification.  Cedarblom and Paulsen: 164', 'explanation', 'The theory which explains does not appeal to underlying causes'),
(51, 1644165520, 3, 'Too Broad', NULL, 'The definition includes items that should not be included.', 'Identify the term being defined. Identify the conditions in the definition. Find an item which meets the condition but is obviously not an instance of the term. \nCedarblom and Paulsen: 182 ', 'definition', 'The definition includes items that should not be included'),
(52, 1644165705, 3, 'Too Narrow', NULL, 'The definition does not include all the items that should be included.', 'Identify the term being defined. Identify the conditions in the definition. Find an item which is an instance of the term but does not meet the conditions.  Cedarblom and Paulsen: 182 ', 'definition', 'The definition does not include all the items that should be included'),
(53, 1644165891, 3, 'Failure to Elucidate', NULL, 'The definition is more difficult to understand than the word or concept being defined.', '     Identify the term being defined. Identify the conditions in the definition. Show that the conditions are no more clearly defined than the term being defined. Cedarblom and Paulsen: 184 ', 'definition', 'The definition is more difficult to understand than the word or concept being defined'),
(54, 1644166053, 3, 'Circular Definition', NULL, 'The definition includes the term being defined as a part of the definition (a circular definition is a special case of a Failure to Elucidate.) ', 'Identify the term being defined. Identify the conditions in the definition. Show that at least one term used in the conditions is the same as the term being defined. Cedarblom and Paulsen: 184 ', 'definition', 'The definition includes the term being defined as a part of the definition'),
(55, 1644166246, 3, 'Conflicting Conditions', NULL, 'The definition is self-contradictory. ', 'Identify the conditions in the definition. Show that they cannot all be true at the same time (in particular, assume that one of the conditions is true, then show from this that another of the conditions must be false). Cedarblom and Paulsen: 186 ', NULL, 'The definition is self-contradictory. Either the terms themselves, or inferences that follow from those terms, are mutually inconsistent.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fallacy`
--
ALTER TABLE `fallacy`
  ADD PRIMARY KEY (`fallacy_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fallacy`
--
ALTER TABLE `fallacy`
  MODIFY `fallacy_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
